api_m/urls.py
from django.urls import path, re_path

from . import views


app_name = 'api-m'
urlpatterns = [
    path('register/', views.register_api, name='register-user'),
    path('login/', views.login_api, name='login-user'),
    path('logout/', views.logout_api, name='logout-user'),
    path('update-password/', views.update_password, name='update-password'),

    path('types/', views.TypeListManager.as_view(), name='device-list'),

    path('devices/', views.DeviceListManager.as_view(), name='device-list'),
    path('devices/<int:pk>', views.DeviceDetailManager.as_view(),
         name='device-detail'),

    path('requests/<int:pk>', views.RequestDetailManager.as_view(),
         name='request-detail'),
    re_path('requests/(?P<term>.*)', views.RequestListManager.as_view(),
            name='request-list'),

    path('actions/', views.ActionListManager.as_view(), name='action-list'),

    path('stages/', views.StageListManager.as_view(), name='stage-list'),

    path('current_user/', views.current_user, name='current-user'),

]

frontend_manager/urls.py
from django.urls import path

from . import views

app_name = 'frontend_manager'

urlpatterns = [
    path('home', views.ManagerHome.as_view(), name='home-page'),
    path('archive', views.CompletedRequests.as_view(),
         name='requests-completed'),

    path('requests/move', views.MoveStage.as_view(), name='request-move-stage'),
    path('requests/<int:pk>', views.RequestInfo.as_view(), name='request-info'),

    path('update-password/', views.UpdatePassword.as_view(),
         name='update-password'),

    path('logout/', views.logout_user, name='logout'),
]

repairs/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api-m/', include('api_m.urls', namespace='api-m')),
    path('user_api/', include('user_api.urls', namespace='user_api')),
    path('', include('user_frontend.urls')),
    path('manager/', include('frontend_manager.urls', namespace='manager')),
]

frontend_manager/models.py
from django.db import models

# Create your models here.

frontend_manager/views.py
import json
import requests

from django.contrib import messages
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views import generic, View

from . utils import get_current_user, get_stages_list


class ManagerHome(generic.TemplateView):
    template_name = 'manager/index.html'

    def get(self, request, *args, **kwargs):
        user = get_current_user(request)
        if not user:
            return HttpResponseRedirect('/login')
        if not user['is_manager']:
            return HttpResponseRedirect('/user/dashboard')
        return super().get(
            super(ManagerHome, self), request, *args, **kwargs
        )

    def get_context_data(self, *args, **kwargs):
        request_list = []
        url = self.request.build_absolute_uri(
            reverse('api-m:request-list', kwargs={'term': 'pending'})
        )
        headers = {
            'Authorization': f'Token {self.request.COOKIES["Token"]}'
        }
        api_response = requests.get(url=url, headers=headers)
        if api_response.status_code == 200:
            request_list = json.loads(api_response.content)
        return {
            'request_list': request_list,
            'email': self.request.session['email']
        }


class CompletedRequests(generic.TemplateView):
    template_name = 'manager/archive.html'

    def get(self, request, *args, **kwargs):
        user = get_current_user(request)
        if not user:
            return HttpResponseRedirect('/login')
        if not user['is_manager']:
            return HttpResponseRedirect('/user/dashboard')
        return super().get(
            super(CompletedRequests, self), request, *args, **kwargs
        )

    def get_context_data(self, *args, **kwargs):
        request_list = []
        url = self.request.build_absolute_uri(
            reverse('api-m:request-list', kwargs={'term': 'completed'})
        )
        headers = {
            'Authorization': f'Token {self.request.COOKIES["Token"]}'
        }
        api_response = requests.get(url=url, headers=headers)
        if api_response.status_code == 200:
            request_list = json.loads(api_response.content)
        return {
            'request_list': request_list,
            'email': self.request.session['email']
        }


class RequestInfo(generic.TemplateView):
    template_name = 'manager/request_detail.html'

    def get(self, request, *args, **kwargs):
        user = get_current_user(request)
        if not user:
            return HttpResponseRedirect('/login')
        if not user['is_manager']:
            return HttpResponseRedirect('/user/dashboard')
        return super().get(
            super(RequestInfo, self), request, *args, **kwargs
        )

    def get_context_data(self, *args, **kwargs):
        service_request = {}
        url = self.request.build_absolute_uri(
            reverse('api-m:request-detail', kwargs={'pk': kwargs['pk']})
        )
        headers = {
            'Authorization': f'Token {self.request.COOKIES["Token"]}'
        }
        api_response = requests.get(url=url, headers=headers)
        if api_response.status_code == 200:
            service_request = json.loads(api_response.content)
        return {
            'request': service_request,
            'stages': get_stages_list(self.request),
            'email': self.request.session['email']
        }


class MoveStage(View):
    def post(self, request, *args, **kwargs):
        user = get_current_user(request)
        if not user:
            return HttpResponseRedirect('/login')
        if not user['is_manager']:
            return HttpResponseRedirect('/user/dashboard')
        data = json.dumps({
            'request': request.POST['request-choice'],
            'to_stage': request.POST['to-stage'],
            'stage_status': request.POST['stage_status'],
            'handler': get_current_user(request).get('id')
        })
        url = request.build_absolute_uri(reverse('api-m:action-list'))
        headers = {
            'Authorization': f'Token {request.COOKIES["Token"]}',
            'Content-type': 'application/json'
        }
        api_response = requests.post(url=url, headers=headers, data=data)
        if api_response.status_code == 201:
            messages.info(request, message="Request updated.")
        else:
            messages.error(request, message="Something went wrong.")
        return HttpResponseRedirect(
            reverse(
                'manager:request-info',
                kwargs={'pk': request.POST['request-choice']}
            )
        )


class UpdatePassword(generic.TemplateView):
    template_name = 'manager/update_password.html'

    def get(self, request, *args, **kwargs):
        user = get_current_user(request)
        if not user:
            return HttpResponseRedirect('/login')
        if not user['is_manager']:
            return HttpResponseRedirect('/user/dashboard')
        return super().get(
            super(UpdatePassword, self), request, *args, **kwargs
        )

    def get_context_data(self, *args, **kwargs):
        return {
            'email': self.request.session['email']
        }

    def post(self, request, *args, **kwargs):
        user = get_current_user(request)
        if not user:
            return HttpResponseRedirect('/login')
        if not user['is_manager']:
            return HttpResponseRedirect('/user/dashboard')
        data = json.dumps({
            'old_password': request.POST.get('password1', ''),
            'new_password': request.POST.get('password2', '')
        })
        url = request.build_absolute_uri(reverse('api-m:update-password'))
        headers = {
            'Authorization': f'Token {request.COOKIES["Token"]}',
            'Content-type': 'application/json'
        }
        api_response = requests.post(url=url, headers=headers, data=data)
        messages.info(request,
                      message=json.loads(api_response.content)['message'])
        if api_response.status_code == 200:
            return HttpResponseRedirect(reverse('manager:home-page'))
        return HttpResponseRedirect(reverse("manager:update-password"))


def logout_user(request):
    headers = {
        'Authorization': f'Token {request.COOKIES["Token"]}'
    }
    url = request.build_absolute_uri(reverse('api-m:logout-user'))
    api_response = requests.post(url=url, headers=headers)
    if api_response.status_code == 200:
        ui_response = HttpResponseRedirect('/')
        ui_response.delete_cookie("Token")
        return ui_response
    return HttpResponseRedirect(reverse('manager:home-page'))

frontend_manager/templates/manager/archive.html
{% extends 'manager/base.html' %}

{% block maincontent %}
    <h2 style="width: 90%; margin: auto;">Completed requests</h2>
    <div id="messages-div">
        {% for message in messages %}
            <span>{{ message }}</span>
        {% endfor %}
    </div>
    <form action="{% url 'manager:request-move-stage' %}" id="next-stage-form" method="POST">
        {% csrf_token %}
        <table id="request-table" >
            {% if request_list %}
            <br>
            <tr>
                <th style="width: 2%;">ID</th>
                <th style="width: 20%;">Device</th>
                <th style="width: 25%;">Description</th>
                <th>Customer</th>
            <th style="width: 20%;">Created</th>
            <th>Completed</th>
        </tr>
        {% for request in request_list %}
        <tr id="row-request-{{request.id}}">
            
            <td><a href="{% url 'manager:request-info' pk=request.id %}">{{request.id}}</a></td>
            <td>{{ request.device.manufacturer }} {{ request.device.model }} {{ request.device.serial_number }}</td>
            <td>{{ request.description }}</td>
            <td><span>{{ request.device.owner.email }}</span></td>
            <td>{{ request.created }}</td>
            {% with request.actions|last as last_action %}
            {{ last_action.key }}
            <td>{{ last_action.timestamp }}</td>
            {% endwith %}
        </tr>
        {% endfor %}
    </table>
    <br>
    {% else %}
        </table>
        <p style="width: 90%; margin: auto;">No requests.</p>
{% endif %}
</form>
</div>
{% endblock %}

frontend_manager/templates/manager/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Manager Console</title>
    {% load static %}
    <link type="text/css" rel="stylesheet" href="{% static 'css/manager/bootstrap-min.css' %}">
    <link type="text/css" rel="stylesheet" href="{% static 'css/manager/styles.css' %}">
    <link type="text/css" rel="stylesheet" href="{% static 'css/manager/base.css' %}">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light " style="background-color: #ec8c11;">
        <a class="navbar-brand ml-5 p-3 text-light" href="{% url 'manager:home-page' %}">Manager Dashboard</a>
        <a class="navbar-brand ml-5 p-3 text-light" href="{% url 'manager:requests-completed' %}">Archive</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto text-center mr-5">
                <li class="nav-item dropdown mr-5">
                    <a class="nav-link dropdown-toggle text-light" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        {{email}}
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <a class="dropdown-item" href="{% url 'manager:update-password' %}">Update Password</a>
                        <a class="dropdown-item" href="{% url 'manager:logout' %}">Logout</a>
                    </div>
                </li>
            </ul>
        </div>
    </nav>
    <main id="main-element">
        {% block maincontent %}
        {% endblock %}
    </main>
</body>
<script type="text/javascript" src="{% static 'js/manager/script.js' %}"></script>
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="{% static 'js/manager/popper-min.js' %}"></script>
<script src="{% static 'js/manager/bootstrap-min.js' %}"></script>
</html>

frontend_manager/templates/manager/index.html
{% extends 'manager/base.html' %}

{% block maincontent %}
    <h2 style="width: 90%; margin: auto;">Pending requests</h2>
    <div id="messages-div">
        {% for message in messages %}
            <span>{{ message }}</span>
        {% endfor %}
    </div>
    {% include 'manager/request_list.html' %}
{% endblock %}

frontend_manager/templates/manager/request_detail.html
{% extends 'manager/base.html' %}

{% block maincontent %}
{% load static %}
<div id="messages-div">
    {% for message in messages %}
        <span>{{ message }}</span>
    {% endfor %}
</div>
<h1 style="width: 90%; margin: auto;"> Service request details</h1>
<!-- Horizontal Steppers -->
<section class="stepper-view box-shadow">
    {% include 'manager/stepper.html' %}
</section>

<table class="no-border grey-background request-detail-table">
    <tr class="no-border flex-column">
        <td class="no-border "><h3>Request Number</h3></td>
        <td class="no-border ">{{request.id}}</td>
    </tr>
    <tr class="no-border flex-column">
        <td class="no-border ">
            <h2 class="no-border ">Device details</h2>
            <p><span class="property-name-span">Type: </span><span>{{request.device.type_of_device.name}}</span></p>
            <p><span class="property-name-span">Manufacturer: </span><span>{{request.device.manufacturer}}</span></p>
            <p><span class="property-name-span">Model: </span><span>{{request.device.model}}</span></p>
            <p><span class="property-name-span">S/No: </span><span>{{request.device.serial_number}}</span></p>
        </td>
    </tr>
    <tr class="no-border flex-column">
        <td class="no-border">
            <h2>Customer details</h2>
            <p class="no-border "><span class="property-name-span">Email: </span><span>{{request.device.owner.email}}</span></p>
        </td>
    </tr>
    <tr class="no-border flex-column">
        <td class="no-border">
            <h2>Description</h2>
            <p class="no-border ">{{request.description}}</p>
        </td>
    </tr>
    <tr class="no-border flex-column">
        <td class="no-border">
            <h2>Status</h2>
            <p class="no-border ">
                Current stage:
                {{request.stage.name}}
            </p>
            <p class="no-border ">{% if request.stage.id != 1 %}Current stage status: {% for d in request.actions %}{% if forloop.last %} {{ d.stage_status }} {% endif %} {% endfor %}{% endif %}</p>
        </td>
    </tr>
</table>
<br>
<form id="next-stage-form-detail" action="{% url 'manager:request-move-stage' %}" method="POST">
    {% csrf_token %}
    <input style="display: none;" name="request-choice" value="{{request.id}}" type="text">
    <input style="display: none;" id="stage-input" name="to-stage" value="{{request.stage.id}}" type="text">
    <label for="description-input">Remarks</label>
    <div>
        <textarea id="description-input" name="stage_status" type="textarea" rows="4" cols="50"></textarea>
        <br>
        <button type="button" onclick="editCurrentStageStatusDetail()" style="margin: auto;">Update current stage status</button>
        <button type="button" onclick="moveNextStageDetail()" style="margin: auto;">Move to next stage</button>
    </div>
</form>



{% endblock %}

frontend_manager/templates/manager/request_list.html
<form action="{% url 'manager:request-move-stage' %}" id="next-stage-form" method="POST">
    {% csrf_token %}
    <table id="request-table" >
        {% if request_list %}
        <br>
        <tr>
            <th></th>
            <th style="width: 2%;">ID</th>
            <th style="width: 20%;">Device</th>
            <th style="width: 25%;">Description</th>
            <th style="width: 20%;">Created</th>
            <th>Customer</th>
            <th>Current stage</th>
        </tr>
        {% for request in request_list %}
            <tr id="row-request-{{request.id}}">
                <td><input class="request-radio-button" type="radio" id="request-{{request.id}}" name="request-choice" value="{{request.id}}"></td>

                <td><a href="{% url 'manager:request-info' pk=request.id %}">{{request.id}}</a></td>
                <td>{{ request.device.manufacturer }} {{ request.device.model }} {{ request.device.serial_number }}</td>
                <td>{{ request.description }}</td>
                <td>{{ request.created }}</td>
                <td><span>{{ request.device.owner.email }}</span></td>
                <td>{{ request.stage.name }}<span id="stage-info-{{request.id}}" style="width: 0;height: 0;visibility: hidden;">{{request.stage.id}}</span></td>
            </tr>
        {% endfor %}
    </table>
    <br>
    <div id="action-description-div">
        <label for="action-description-input">Remarks</label>
        <textarea id="action-description-input" name="stage_status" maxlength="1000" rows="3" cols="50" required></textarea>
        <input id="stage-input" style="display: none;" type="text" name="to-stage">
    </div>
    <br>
    <br>
    <div style="width: 90%; margin: auto;">
        <button type="button" onclick="editCurrentStageStatus()" >Edit current stage status</button>
        <button type="button" onclick="moveNextStage()" >Move to next stage</button>
    </div>
    {% else %}
        </table>
        <p style="width: 90%; margin: auto;">No requests pending.</p>
    {% endif %}
</form>
</div>

frontend_manager/templates/manager/stepper.html
{% load static %}
<link type="text/css" rel="stylesheet" href="{% static 'css/manager/stepper.css' %}"></link>
<div class="container flex-row">
    <ul class="progressbar">
        {% widthratio 100 stages|length 1 as line_width %}
        {% for stage in stages %}
            <li class="{% if request.stage.id > stage.id %} active {% elif request.stage.id == stage.id %} in-progress {% endif %}" style="width: {{line_width|add:'-1'}}%;">{{stage.name}}</li>
        {% endfor %}
    </ul>
</div>

frontend_manager/templates/manager/update_password.html
{% extends 'manager/base.html' %}
{% block maincontent %}
<div class="container mt-5">
<form method="post">
    {% for message in messages %}
        <p>{{message}}</p>
    {% endfor %}
       {% csrf_token %}
    <h3 class="text-center">Update Password</h3>
       <p class="text-center text-danger">{{error_msg}}</p>
    <div class="form-group">
        <label for="current_password">Current Password</label>
        <input type="password" class="form-control" id="current_password" placeholder="Enter current password"name="password1" autocomplete="off">
    </div>
    <div class="form-group">
        <label for="new_password">New Password</label>
        <input type="password" class="form-control" id="new_password" placeholder="Enter New password"name="password2" autocomplete="off">
    </div>
     <button type="submit" class="btn btn-primary">Update</button>
   </form>
</div>
{% endblock %}